### ISSUE TITLE
Add support json5 or yaml

### ISSUE THREAD

**Issue by webspilka** [kaisermann/svelte-i18n#126]
I can't use comments or multiline text in my json files. 
What you think about add option json5 formatter or yaml files support for translation files?
```yaml
key: #comment 1
   - value line 1
   #comment 2
   - value line 2
   #comment 3
   - value line 3
Key: >-
  This is a very long sentence
  that spans several lines in the YAML
  but which will be rendered as a string
  with NO carriage returns.
```
